# Label names for retrieve the correct news category
LABEL_NAMES:
  0: 'International News'
  1: 'Business'
  2: 'Technology'
  3: 'Entertainment'
  4: 'Sports'
  5: 'General News'
  6: 'Health'

RSS_TO_LABEL:
    'world': 0
    'europe': 0
    'politics': 0
    'elections': 0
    'us': 0
    'business': 1
    'tech': 2
    'science': 2
    'entertainment': 3
    'sports': 4
    'cnn_topstories': 5
    'health': 6

# Random seed for reproducibility
RANDOM_STATE: 42

CONTEXT_INJECTION: True

USE_CATBOOST: True

USE_CHI2: False

TUNING: False


TFIDF_PARMAS:
  'max_features':  15000
  'ngram_range':  (1, 3)
  'min_df':  5
  'max_df':  0.7
  'token_pattern':  r'(?u)\b[a-zA-Z]{3,}\b'
  'stop_words':  'english'
  'sublinear_tf':  True

CATBOOST_PARAMS:
  'sigma': 0.9

CHI2_PARAMS:
  'chi2_k': 10000


